runtime: python37
instance_class: F1

default_expiration: "5m"

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 0
  max_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  LAMBDA_URL: https://sl1cpqn8tg.execute-api.us-west-2.amazonaws.com/prod/predict


handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
  

entrypoint: gunicorn -b :$PORT cv-demo:application -w 4 --timeout 120